# Mathematics

+ Mathematics deals with numbers, logic and formal system.
+ Linear Algebra and Probability are two major sub-fields under mathematics that are used extensively in Machine Learning.
+ Linear algebra deals with mathematical objects and structures like vectors, matrices, lines, planes, hyperplanes, and vector spaces.
+ The theory of probability is a mathematical field and framework used for studying and quantifying events of chance and uncertainty and deriving theorems and axioms from the same.

## Scalar
+ A scalar usually denotes a single number as opposed to a collection of numbers.
+ Ex. x = 5 or x ∈ R, where x is the scalar element pointing to a single number or a real-valued single number.

## Vector
+ Vectors can be mathematically denoted as x = [x1, x2, …, xn], which basically tells us that x is a one-dimensional vector having n elements in the array.
+ Python lists as well as numpy based arrays can be used to represent vectors.
+ Numpy ndarray is a multidimensional array object which is the core data container for all of the numpy operations.

In [1]:
#representation of simple vector
x = [1, 2, 3, 4, 5]
#display the vector
x

[1, 2, 3, 4, 5]

In [2]:
#import numpy for numerical computation
import numpy as np
#assigning values to array x
x = np.array([1, 2, 3, 4, 5])
#view array x
print(x)
#view the type of array 
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Matrix

+ A matrix is a two-dimensional structure that basically holds numbers. It’s also often referred to as a 2D array.
+ Matrices can be easily represented as list of lists in Python and we can leverage the numpy array structure as depicted below.

In [3]:
#assigning values to matrix m
m = np.array([[1, 5, 2],
              [4, 7, 4],
              [2, 0, 9]])
#view matrix m
print(m)

[[1 5 2]
 [4 7 4]
 [2 0 9]]


In [4]:
#view dimensions of the matrix m
print(m.shape)

(3, 3)


In [5]:
#view matrix transpose (\n is for changing the line)
print('Matrix Transpose:\n', m.transpose())

Matrix Transpose:
 [[1 4 2]
 [5 7 0]
 [2 4 9]]


In [6]:
#view matrix determinant calculation
print ('Matrix Determinant:', np.linalg.det(m))

Matrix Determinant: -105.00000000000006


In [7]:
#view matrix inverse
m_inv = np.linalg.inv(m)
print ('Matrix inverse:\n', m_inv)

Matrix inverse:
 [[-0.6         0.42857143 -0.05714286]
 [ 0.26666667 -0.04761905 -0.03809524]
 [ 0.13333333 -0.0952381   0.12380952]]


In [8]:
#identity matrix (result of matrix * matrix_inverse)
iden_m =  np.dot(m, m_inv)
iden_m = np.round(np.abs(iden_m), 0)

#view product of matrix and its inverse
print ('Product of matrix and its inverse:\n', iden_m)

Product of matrix and its inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Eigen Decomposition

+ This is basically a matrix decomposition process such that we decompose or break down a matrix into a set of eigen vectors and eigen values.
+ Mathematically this can be denoted by Mv = λv where M is our matrix, v is the eigen vector and λ is the corresponding eigen value.

In [9]:
#eigen decomposition of the matix
m = np.array([[1, 5, 2],
              [4, 7, 4],
              [2, 0, 9]])

#break down the matrix into eigen values and eigen vectors
eigen_vals, eigen_vecs = np.linalg.eig(m)

#view eigen values
print('Eigen Values:', eigen_vals, '\n')
#view Eigen vectors
print('Eigen Vectors:\n', eigen_vecs)

Eigen Values: [-1.32455532 11.32455532  7.        ] 

Eigen Vectors:
 [[-0.91761521  0.46120352 -0.46829291]
 [ 0.35550789  0.79362022 -0.74926865]
 [ 0.17775394  0.39681011  0.46829291]]


## Singular Value Decomposition

+ The process of singular value decomposition, also known as SVD, is another matrix decomposition or factorization process such that we are able to break down a matrix to obtain singular vectors and singular values.

In [10]:
#SVD
m = np.array([[1, 5, 2],
              [4, 7, 4],
              [2, 0, 9]])

#main components of decomposition equation are U,S,VT
U, S, VT = np.linalg.svd(m)

#view message "Getting SVD outputs"
print ('Getting SVD outputs:-')
#view the value of U
print('U:\n', U,'\n')
#view the value of S
print('S:\n', S,'\n')
#view the value of VT
print('VT:\n', VT,'\n')

Getting SVD outputs:-
U:
 [[ 0.3831556  -0.39279153  0.83600634]
 [ 0.68811254 -0.48239977 -0.54202545]
 [ 0.61619228  0.78294653  0.0854506 ]] 

S:
 [12.10668383  6.91783499  1.25370079] 

VT:
 [[ 0.36079164  0.55610321  0.74871798]
 [-0.10935467 -0.7720271   0.62611158]
 [-0.92621323  0.30777163  0.21772844]] 



# Statistics

+ The field of statistics can be defined as a specialized branch of mathematics that consists of frameworks and methodologies to collect, organize, analyze, interpret, and present data. Generally this falls more under applied mathematics and borrows concepts from linear algebra, distributions, probability theory, and inferential methodologies.
+ The core component of any statistical process is data.

## Descriptive Statistics

+ Descriptive statistics is used to understand basic characteristics of the data using various aggregation and summarization measures to describe and understand the data better.
+ These could be standard measures like mean, median, mode, skewness, kurtosis, standard deviation, variance, and so on.

In [11]:
#import scipy for statistics computation
import scipy as sp
from scipy import stats 

#get random integers in data
nums = np.random.randint(1,20, size=(1,15))[0]
#view the data
print('Data: ', nums)

Data:  [15 12 10 11 17 19 10  2  8  6 16 18  6 18 13]


In [12]:
#get descriptive stats
print ('Mean:', sp.mean(nums))
#view median value of the data
print ('Median:', sp.median(nums))
#view mode value of the data
print ('Mode:', sp.stats.mode(nums))
#view standard deviation value of the data
print ('Standard Deviation:', sp.std(nums))
#view variance value of the data
print ('Variance:', sp.var(nums))
#view skew value of the data
print ('Skew:', sp.stats.skew(nums))
#view Kurtosis value of the data
print ('Kurtosis:', sp.stats.kurtosis(nums))

Mean: 12.066666666666666
Median: 12.0
Mode: ModeResult(mode=array([6]), count=array([2]))
Standard Deviation: 4.959390643572611
Variance: 24.595555555555556
Skew: -0.3250785062358711
Kurtosis: -0.9077010415881639


# Data Retrieval

+ This is mainly data collection, extraction, and acquisition from various data sources and data stores.
+ Either we can give the path of csv file or we can upload the data.
+ df is data frame which is most important and useful data structure used for almost all kind of data representation and manipulation in pandas

In [13]:
#import pandas for data manipulation, wrangling and analysis
import pandas as pd
# turn of warning messages
pd.options.mode.chained_assignment = None  #default='warn'

# get data from student_records.csv file
df = pd.read_csv('student_records.csv')
df

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

# Data Preparation

+ In this step, we pre-process the data, clean it, wrangle it, and manipulate it as needed.
+ Initial exploratory data analysis is also carried out.

## Feature Extraction and Engineering

+ We extract important features or attributes from the raw data and even create or engineer new features from existing features.

In [14]:
#Extracting the existing features from the dataset and the outcomes in separate variables
#get features and corresponding outcomes
feature_names = ['OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore']
training_features = df[feature_names]

outcome_name = ['Recommend']
outcome_labels = df[outcome_name]

In [15]:
#view features
training_features

OverallGrade Obedient  ResearchScore  ProjectScore
0            A        Y             90            85
1            C        N             85            51
2            F        N             10            17
3            B        Y             75            71
4            E        N             20            30
5            A        Y             92            79
6            B        Y             60            59
7            C        Y             75            33

In [16]:
#view outcome labels
outcome_labels

Recommend
0       Yes
1       Yes
2        No
3        No
4        No
5       Yes
6        No
7        No

In [17]:
#list down features based on type
numeric_feature_names = ['ResearchScore', 'ProjectScore']
categoricial_feature_names = ['OverallGrade', 'Obedient']

In [18]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

#fit scaler on numeric features
ss.fit(training_features[numeric_feature_names])

#scale numeric features now
training_features[numeric_feature_names] = ss.transform(training_features[numeric_feature_names])

#view updated feature set
training_features

OverallGrade Obedient  ResearchScore  ProjectScore
0            A        Y       0.899583      1.376650
1            C        N       0.730648     -0.091777
2            F        N      -1.803390     -1.560203
3            B        Y       0.392776      0.772004
4            E        N      -1.465519     -0.998746
5            A        Y       0.967158      1.117516
6            B        Y      -0.114032      0.253735
7            C        Y       0.392776     -0.869179

In [19]:
#After successfully scaling the numeric features, handing of the categorical features
training_features = pd.get_dummies(training_features, columns=categoricial_feature_names)
#view the updated feature set with the newly engineered categorical variables (One hot encoding)
training_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_B  \
0       0.899583      1.376650               1               0   
1       0.730648     -0.091777               0               0   
2      -1.803390     -1.560203               0               0   
3       0.392776      0.772004               0               1   
4      -1.465519     -0.998746               0               0   
5       0.967158      1.117516               1               0   
6      -0.114032      0.253735               0               1   
7       0.392776     -0.869179               0               0   

   OverallGrade_C  OverallGrade_E  OverallGrade_F  Obedient_N  Obedient_Y  
0               0               0               0           0           1  
1               1               0               0           1           0  
2               0               0               1           1           0  
3               0               0               0           0           1  
4               0               1               0           1           0  
5               0               0               0           0           1  
6               0               0               0           0           1  
7               1               0               0           0           1

In [22]:
#get list of new categorical features
categorical_engineered_features = list(set(training_features.columns) - set (numeric_feature_names))

# Modeling

+ In the process of modeling, we usually feed the data features to a Machine Learning method or algorithm and train the model, typically to optimize a specific cost function in most cases with the objective of reducing errors and generalizing the representations learned from the data.
+ The following code depicts how to build the supervised model. We will build a simple classification (supervised) model based on our feature set by using the logistic regression algorithm.

In [23]:
from sklearn.linear_model import LogisticRegression
import numpy as np

#fit the model
lr = LogisticRegression() 
model = lr.fit(training_features, np.array(outcome_labels['Recommend']))
#view model parameters
model

C:\Users\INTEL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

## Model Evaluation and tuning

+ Built models are evaluated and tested on validation datasets and, based on metrics like accuracy, F1 score, and others, the model performance is evaluated.
+ Models have various parameters that are tuned in a process called hyperparameter optimization to get models with the best and optimal results.

In [24]:
#simple evaluation on training data
pred_labels = model.predict(training_features)
actual_labels = np.array(outcome_labels['Recommend'])

#evaluate model performance
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

print('Accuracy:', float(accuracy_score(actual_labels, pred_labels))*100, '%')
print('Classification Stats:')
print(classification_report(actual_labels, pred_labels))

Accuracy: 100.0 %
Classification Stats:
              precision    recall  f1-score   support

          No       1.00      1.00      1.00         5
         Yes       1.00      1.00      1.00         3

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



## Model Deployment

+ Selected models are deployed in production and are constantly monitored based on their predictions and results.
+ We built our first supervised learning model, and to deploy this model typically in a system or server, we need to persist the model.
+ We also need to save the scalar object we used to scale the numerical features since we use it to transform the numeric features of new data samples.

In [25]:
#store the model and scalar objects
from sklearn.externals import joblib
import os
#save models to be deployed on your server
if not os.path.exists('Model'):
    os.mkdir('Model')
if not os.path.exists('Scaler'):
    os.mkdir('Scaler') 
    
joblib.dump(model, r'Model/model.pickle') 
joblib.dump(ss, r'Scaler/scaler.pickle') 

C:\Users\INTEL\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


['Scaler/scaler.pickle']

# Prediction in Action

+ To start predictions, we need to load our model and scalar objects into memory.

In [26]:
#load model and scaler objects
model = joblib.load(r'Model/model.pickle')
scaler = joblib.load(r'Scaler/scaler.pickle')

In [27]:
#data retrieval
new_data = pd.DataFrame([{'Name': 'Nathan', 'OverallGrade': 'F', 'Obedient': 'N', 'ResearchScore': 30, 'ProjectScore': 20},
                  {'Name': 'Thomas', 'OverallGrade': 'A', 'Obedient': 'Y', 'ResearchScore': 78, 'ProjectScore': 80}])
new_data = new_data[['Name', 'OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore']]
new_data

Name OverallGrade Obedient  ResearchScore  ProjectScore
0  Nathan            F        N             30            20
1  Thomas            A        Y             78            80

In [28]:
#data preparation
prediction_features = new_data[feature_names]

#scaling
prediction_features[numeric_feature_names] = scaler.transform(prediction_features[numeric_feature_names])

#engineering categorical variables
prediction_features = pd.get_dummies(prediction_features, columns=categoricial_feature_names)

#view feature set
prediction_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_F  Obedient_N  \
0      -1.127647     -1.430636               0               1           1   
1       0.494137      1.160705               1               0           0   

   Obedient_Y  
0           0  
1           1

In [40]:
#final feature set for new students
#add missing categorical feature columns
current_categorical_engineered_features = set(prediction_features.columns) - set(numeric_feature_names)
missing_features = set(categorical_engineered_features) - current_categorical_engineered_features
for feature in missing_features:
    #add zeros since feature is absent in these data samples
    prediction_features[feature] = [0] * len(prediction_features)
#view final feature set
prediction_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_F  Obedient_N  \
0      -1.127647     -1.430636               0               1           1   
1       0.494137      1.160705               1               0           0   

   Obedient_Y  OverallGrade_C  OverallGrade_B  OverallGrade_E  
0           0               0               0               0  
1           1               0               0               0

In [41]:
#predict using model
predictions = model.predict(prediction_features)

## display results
new_data['Recommend'] = predictions
new_data

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0  Nathan            F        N             30            20        No
1  Thomas            A        Y             78            80       Yes